---
_extends: .github

repository:
  name: hs-schema
  description: Encoding-independent schemas for Haskell data types
  homepage: https://hackage.haskell.org/package/schema
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "build / cabal"
          - "build / stack"
