---
language: generic
dist: xenial
os: linux

env:
  global:
    # HACKAGE_USERNAME=[secure]
    - secure: "PhdF4y2VSihONeeRJ36fqfAsy7hL9ORJjiz1T3l/3soMUWMtOTRxa+TfzrOOuRK1U04z0JfNuWcTeyW+I0U95TJNgEw0WGGGSTGMWamTOkB0WPSv5gFFT1jUGxDEii+yvrItAIdatCVN3aiKCyy7WSEfraHocG3zVfeeAy5Gmn1Y4+mo7KpbzU666by6YjPlVHyrJUgBmej8eomnV61h9ggIU+atjee3hyhllD9MjeO8v9hPjUKaddYxtXtCq440VqTvC1Xg9OG+qp0RMZceCc3uSw/iRMt0pAMwkHjolzoyMnlsa/wWaZ+jeoM0lpPuFg7NJL1ZkFaLzOO3kTG2bNZgQDWm47/eorOCwxZ//u7aMYTZHnrRuKGUO3C5tCksFqAL+Oiwwl6dPTT2gjzf0scKbePjIYIo0YeSwOOOKGM6exol5cnWnJKEfQz3FhCeiwKpTkZXfvEhNqSsF+ATpe4omKn+BR5Ig74+4Rzsim0FCghazrVgS50ED5KaizNN4tcDMC7OjLn204wEtIP/gWfeQJHVs87kpMPpcU56QFiDynnizpfGAH2P5QXRyON/s6oP98WBnlYIO3VGowEWtYldNVcrFPMgP3ulcaNz0709ed/m0PNI6hQafbCjyD0J8zWcE0ssnrMgAroBHLTcDuO3dasfmBujm+0PUhpjVd0="
    # HACKAGE_PASSWORD=[secure]
    - secure: "gNfKCo/wSuCTaME2TEJt7QZHRPhHeUy3uOpngg4CRleULeWL0H8UsVhdSa88fw5Qhh/ft3CI8uJ/rCgCsdtuQMOXyeoTBaFrDReuGLbEdvT79GugABc7Tdq90/r6KsWXB8VdVeT6oad37eff7LH8aRvJoB9YwZwlA8MhPsIuzMteotkZaG76kwk/vi4T2lUaPuK2ZIKxZAX3flVXJMD4ZnAukTk20lyAwTWMubSO+ET5iD9w2DZPGzFQYp6nLjVnFVnTe4wEUP4UA87zHiO4p+IfHPd7E3GVmPSoDhlsMHt7xIK51JMZg7sOGMNfR2tFJHPkGBpGLApbWExAgU7wMx3ttau8gx5tFBGtyrjjoZkEsHiipRdP/53K/KZhzcALaE6c5wdYzAWohkKjnWx8DGWaI8Yd6XoQgF6wuYZ2hevrbK0jhY5yggc6H122QR8ZIArRql2HT7F+anW64LnpgVdI9J5OGrx+hS+7XzluOLyeqMiIBEFXgDzLYV8BsIHIHDdp6ONpYhnNiq4HU43PBKbd5nfaFB9rbs6A4ipapRrwZLxE3z7SCl1yuX43oWMpVNTv0cjRfZWUDCBAqnLZhr1EWEPIyFQdAdb3UHhObtk5q5Ed1690c0FL1PFxdN3YQWyRPt/ZxQn4RsptczhnpZ+Wot9M0YnbCJO8KUPsIOE="

cache:
  directories:
    - $HOME/.stack

script: eval $(bash <(curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell-script))

deploy:
  provider: releases
  token:
    secure: "BEqmb7pH28obcC6ECRIfo+ljbRVipdwncGRJTphlOHpQNFH6JHnrtVVINHGy6ikxRYXnI7wGNzl1mbzO2sADutoLJJG5fL9p2dD/7QXSiXDTDA/smUJH9RWCjED6/8oGF65vrOpzL6AieBmhH9oujVvVkBODJpJf7y7rJgLRsTLpV5edNP01gxx6CYaJWSPDp8dv8Azc10MTAqG6R1w6dAvD1oNpVjeAXb7gnCkjv97Nw7PJlL/VvZ581fX3mowd5BbO1v01xlhtuxNJ4Q47DmpCE55N1nPhU+7s2Ez1mk9qCfkGcQwpSlug7f9WboRCL+R+EYtFFaVzeg6zmOIVn9+5GNQDcj5DE7r+1AatT/+7REb+NWxoq8CyyvD+i+jiEK04v5wUA/vaKaFua6JC5gk5tCNVqJjIuBlgehMFvLACQ/NWn3OkC9Tsvgq11lZaJuP6Q/waHsR1iL2uME4LXXKUQiyczgTdIvxa90wCtjcxxVH8OctpKLF/yNTtVJm4GHE8z9MR0+HHwyIFaZQ5o1kFXbx5HxtPWnX8YZVEwDJM/XVr9TxcMkFzh0iaPJG2V7WESdlHKphE0HLmlMJkHq6qA6Qddu9QhdWEvRpyEZ5o8EWD0k48WHGVIyNKWME0okw1U9Hj9a/wIFmNdwP03I+euRzP33iAfjECO+AgHvs="
  file: $PACKAGE-$VERSION.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-schema
    tags: true

after_deploy: bash <(curl -s https://raw.githubusercontent.com/TokTok/hs-tools/master/bin/travis-haskell-deploy)

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
